"""add origin name for PostImage model

Revision ID: 7b0b90272c2c
Revises: 06071add3ace
Create Date: 2026-05-12 19:54:18.498113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0b90272c2c'
down_revision: Union[str, Sequence[str], None] = '06071add3ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_image', sa.Column('origin_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_image', 'origin_name')
    # ### end Alembic commands ###
