from typing import Any, Protocol

from auth.application.dto.jwt import JwtDTO
from auth.application.dto.user import CreateUserDTO, UserDTO


class UnitOfWork(Protocol):
    async def commit(self): ...

    async def rollback(self): ...


class IPasswordService(Protocol):
    def encrypt_pwd(self, input_pwd: str) -> bytes: ...
    def check_pwd(self, input_pwd: str, db_pwd: bytes) -> bool: ...


class IUserService(Protocol):
    async def get_user_by_email(self, email: str) -> UserDTO: ...
    async def check_user_email_exists(self, email: str) -> bool: ...
    async def create_user(
        self, user: CreateUserDTO, pwd_converter: IPasswordService
    ) -> int: ...


class IJwtService(Protocol):
    async def get_by_user_id(self, user_id: int) -> JwtDTO: ...
    def create_pair(self, payload: dict[str, Any]) -> JwtDTO: ...
    def decode_refresh(self, refresh_token: str) -> dict[str, Any]: ...
    def decode_access(self, access_token: str) -> dict[str, Any]: ...
